# name: Check Upstream Updates
# on:
#   schedule:
#     - cron: '0 * * * *'  # 每小时检查一次
#   push:  # 或通过 push 事件触发
#   workflow_dispatch:
  
# jobs:
#   check-updates:
#     runs-on: ubuntu-latest
#     steps:
#       - name: Checkout code
#         uses: actions/checkout@v4
#         with:
#           fetch-depth: 0  # 获取完整提交历史
#       - name: Fetch upstream
#         run: git remote add upstream https://github.com/Fansirsqi/Sesame-TK.git && git fetch upstream
#       - name: Compare branches
#         id: compare
#         run: |
#           if [ $(git rev-parse HEAD) != $(git rev-parse upstream/main) ]; then
#             echo "has_updates=true" >> $GITHUB_OUTPUT
#           fi
#       - name: Trigger Android Workflow
#         if: steps.compare.outputs.has_updates == 'true'
#         uses: actions/github-script@v6
#         with:
#           script: |
#             await github.rest.actions.createWorkflowDispatch({
#               owner: context.repo.owner,
#               repo: context.repo.repo,
#               workflow_id: 'android.yml',
#               ref: 'main'
#             })
